services:
  # FastAPI Backend
  - type: web
    name: bengalurutenants-api
    runtime: python
    region: singapore
    plan: free
    branch: main
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ENVIRONMENT
        value: production
      # Database - You'll add this in Render dashboard
      - key: DATABASE_URL
        sync: false
      # Authentication
      - key: SECRET_KEY
        generateValue: true
        length: 32
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_HOURS
        value: "168"
      - key: CORS_ORIGINS
        value: "https://openreviews.in,https://www.openreviews.in,http://localhost:3000,https://bengalurutenants-in.vercel.app,https://bengalurutenants-in-rudra-khares-projects.vercel.app"
      - key: MAGIC_TOKEN_EXPIRE_SECONDS
        value: "600"
      # Frontend URL - Update after Vercel deployment
      - key: FRONTEND_URL
        value: "https://bengalurutenants-in.vercel.app"
      # Cloudflare R2 Storage
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_BUCKET
        sync: false
      # Email Configuration (SMTP2GO)
      - key: MAIL_USERNAME
        value: "bengalurutenants"
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        value: "noreply@bengalurutenants.social"
      - key: MAIL_PORT
        value: "2525"
      - key: MAIL_SERVER
        value: "smtp.smtp2go.com"
      - key: MAIL_STARTTLS
        value: "true"
      - key: MAIL_SSL_TLS
        value: "false"
      - key: MAIL_USE_CREDENTIALS
        value: "true"
      # Google Maps API
      - key: GOOGLE_MAPS_API_KEY
        sync: false
